apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dtp.fullname" . }}
  labels:
    app: {{ template "dtp.name" . }}
    chart: {{ template "dtp.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ template "dtp.name" . }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "dtp.name" . }}
        chart: {{ template "dtp.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      containers:
      - name: dtp
        image: cbmckni/dtp
        args: ["sleep", "infinity"]
        volumeMounts:
        - name: vol-1
        {{ if .Values.NewPVC.Enabled }}
          mountPath: {{ .Values.NewPVC.Path }}
        {{ else if .Values.ExistingPVC.Enabled }}
          mountPath: {{ .Values.ExistingPVC.Path }}
        {{ end }}
        {{ if .Values.iRODS.Enabled }}
        - name: ienv
          mountPath: "/"
        {{ end }}
      restartPolicy: Always
      volumes:
        {{ if .Values.NewPVC.Enabled }}
        - name: vol-1
          persistentVolumeClaim:
            claimName: {{ .Values.NewPVC.Name }}
        {{ end }}
        {{ if .Values.ExistingPVC.Enabled }}
        - name: vol-1
          persistentVolumeClaim:
            claimName: {{ .Values.ExistingPVC.Name }}
        {{ end }}
        {{ if .Values.iRODS.Enabled }}
        - name: ienv
          secret:
            secretName: irods
            defaultMode: 256
        {{ end }}
