apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dtp.fullname" . }}
  labels:
    app: {{ template "dtp.name" . }}
    chart: {{ template "dtp.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: {{ template "dtp.name" . }}
      instance: {{ .Values.Instance }}
  template:
    metadata:
      labels:
        app: {{ template "dtp.name" . }}
        chart: {{ template "dtp.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
    spec:
      containers:
      - name: dtp
        image: cbmckni/dtp
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "echo 'cd {{ template "pvcPath" . }}' >> ~/.bashrc && source ~/.bashrc && sleep infinity" ]
        volumeMounts:
        - name: vol-1
          mountPath: {{ template "pvcPath" . }}
        {{ if .Values.iRODS.Enabled }}
        - name: ienv
          mountPath: "/etc/.irods"
        env: 
            - 
              name: IRODS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: irods
                  key: IRODS_PASSWORD
        {{ end }}
      restartPolicy: Always
      volumes:
        - name: vol-1
          persistentVolumeClaim:
            claimName: {{ template "pvcName" . }}
        {{ if .Values.iRODS.Enabled }}
        - name: ienv
          secret:
            secretName: irods
            defaultMode: 256
        {{ end }}


# Variables

{{- define "pvcPath" -}}
{{- if .Values.NewPVC.Enabled }}{{ .Values.NewPVC.Path }}{{ else }}{{ .Values.ExistingPVC.Path }}{{ end }}
{{- end -}}

{{- define "pvcName" -}}
{{- if .Values.NewPVC.Enabled }}{{ .Values.NewPVC.Name }}{{ else }}{{ .Values.ExistingPVC.Name }}{{ end }}
{{- end -}}


