{{ if .Values.NewPVC.Enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.NewPVC.Name }}
  labels:
    app: {{ template "nextflow-api.name" . }}
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.NewPVC.StorageClass }}
  resources:
    requests:
      storage: {{ .Values.NewPVC.Size }}
{{ end }}
